# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyTest Whole JIT

on:
  push:
    branches: [ "tristate", "main", "master" ]
  pull_request:
    branches: [ "tristate", "main", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7
      uses: actions/setup-python@v3
      with:
        python-version: "2.7"
    - name: Checkout PyPy
      uses: actions/checkout@v3
      with:
        repository: mozillazg/pypy
        path: pypy
    - name: install dependencies
      run: |
        python -m pip install rply hypothesis
    - name: Test with pytest
      run: |
        python pypy/pytest.py rpython/jit/
